import {
  accessories,
  activity,
  activityPersons,
  bigAnimals,
  birdAnimals,
  bodyParts,
  clothing,
  domesticAnimals,
  drinksAndFoodObjects,
  freshFood,
  insectAnimals,
  jobs,
  music,
  nature,
  objects1,
  objects2,
  objects3,
  objects4,
  otherAnimals,
  phantasy,
  processedFood,
  smileysForGame,
  splitEmojis,
  sport,
  sweets,
  travelAndPlaces,
  vehicles,
  waterReptileAnimals,
  weatherAndEarth,
} from '../game-tools/emoji-util';

export enum EmojiType {
  Activity,
  Animals,
  BodyAndFace,
  Clothing,
  Food,
  Nature,
  Objects,
  Persons,
  Travel,
}

export interface EmojiCategory {
  label: string;
  type: EmojiType;
  emojis: string[];
}

export const emojiCategories: EmojiCategory[] = [
  { label: 'Sport Objects', type: EmojiType.Activity, emojis: splitEmojis(sport) },
  { label: 'Activity Objects', type: EmojiType.Activity, emojis: splitEmojis(activity) },
  { label: 'Music Objects', type: EmojiType.Activity, emojis: splitEmojis(music) },
  { label: 'Activity Persons', type: EmojiType.Activity, emojis: splitEmojis(activityPersons) },
  { label: 'Water Animals and reptiles', type: EmojiType.Animals, emojis: splitEmojis(waterReptileAnimals) },
  { label: 'Birds and air', type: EmojiType.Animals, emojis: splitEmojis(birdAnimals) },
  { label: 'Insects', type: EmojiType.Animals, emojis: splitEmojis(insectAnimals) },
  { label: 'Domestic Animals', type: EmojiType.Animals, emojis: splitEmojis(domesticAnimals) },
  { label: 'Big Animals', type: EmojiType.Animals, emojis: splitEmojis(bigAnimals) },
  { label: 'Other Wild Animals', type: EmojiType.Animals, emojis: splitEmojis(otherAnimals) },
  { label: 'Body parts', type: EmojiType.BodyAndFace, emojis: splitEmojis(bodyParts) },
  { label: 'Smileys', type: EmojiType.BodyAndFace, emojis: splitEmojis(smileysForGame) },
  { label: 'Clothing', type: EmojiType.Clothing, emojis: splitEmojis(clothing) },
  { label: 'Accessories', type: EmojiType.Clothing, emojis: splitEmojis(accessories) },
  { label: 'Fresh Food', type: EmojiType.Food, emojis: splitEmojis(freshFood) },
  { label: 'Processed Food', type: EmojiType.Food, emojis: splitEmojis(processedFood) },
  { label: 'Sweets', type: EmojiType.Food, emojis: splitEmojis(sweets) },
  { label: 'Drinks and food objects', type: EmojiType.Food, emojis: splitEmojis(drinksAndFoodObjects) },
  { label: 'Nature', type: EmojiType.Nature, emojis: splitEmojis(nature) },
  { label: 'Weather', type: EmojiType.Nature, emojis: splitEmojis(weatherAndEarth) },
  { label: 'Objects 1', type: EmojiType.Objects, emojis: splitEmojis(objects1) },
  { label: 'Objects 2', type: EmojiType.Objects, emojis: splitEmojis(objects2) },
  { label: 'Objects 3', type: EmojiType.Objects, emojis: splitEmojis(objects3) },
  { label: 'Objects 4', type: EmojiType.Objects, emojis: splitEmojis(objects4) },
  { label: 'Jobs', type: EmojiType.Persons, emojis: splitEmojis(jobs) },
  { label: 'Phantasy', type: EmojiType.Persons, emojis: splitEmojis(phantasy) },
  { label: 'Vehicles', type: EmojiType.Travel, emojis: splitEmojis(vehicles) },
  { label: 'Travel', type: EmojiType.Travel, emojis: splitEmojis(travelAndPlaces) },
];
